#! /usr/bin/python
# -*- coding: utf-8 -*-
"""
# convert_color_format.py
# Convert color format in Traffic-control-device.gpl to a string format
Copyright (C) February 2020 George Zhang

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""

import simplestyle

fn = 'Traffic-control-device.gpl'
fout = 'color_strings.txt'

fr = open(fn, "r")
fw = open(fout, "w")

for i, line in enumerate(fr, start=1):
    if i > 3:
        t = line.split()
        t = [item.lower() for item in t ]
        color_value = simplestyle.formatColor3i(int(t[0]), int(t[1]), int(t[2]))
        color_name = '_'.join(t[3:])

        fw.write("'{}': '{}',\n".format(color_name, color_value))


# GIMP Palette
# Name: Traffic Control Devices
# # generated by goTrafficSign.com
#  35  31  32  Sign Black
#   0  86 150  Blue
# 121  69  00  Brown
# 241  94 124  Fluorescent Pink
# 193 215  46  Fluorescent Yellow-Green
#   0 111  81  Green
# 244 145  30  Orange
# 108  39  124 Purple
# 191  46  26  Red
# 255 255 255  White
# 255 210  79  Yellow
# 255 127  80  Coral (Reserved)
#  90 147 193  Light Blue (Reserved)
#   0   0   0  Black Ink
# 255   0   0  Red Ink
#   0   0 255  Blue Ink
